# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Class-Loader
version:      0.15
version_from: lib/DBIx/Class/Loader.pm
installdirs:  site
requires:
    DBI:                           1.3
    DBIx::Class:                   0.04001
    Lingua::EN::Inflect:           0
    Test::More:                    0.32
    Text::Balanced:                0
    UNIVERSAL::require:            0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
